//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsEffectDatabaseConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.departments = new HashSet<department>();
        }
    
        public int comp_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<department> departments { get; set; }
    }
}
