//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsEffectDatabaseConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int dept_id { get; set; }
        public string name { get; set; }
        public Nullable<int> fk_company_comp_id { get; set; }
        public Nullable<int> fk_location_location_id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
